mariadb:
  image: mariadb:latest
  ports:
    - "127.0.0.1:3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: testpw
    MYSQL_DATABASE: seopanel
  tty: true
  stdin_open: true

seopanel:
  build: .
  ports:
    - "8080:80"
  links:
    - mariadb
  environment:
    DB_HOST: "mariadb"
    DB_NAME: "seopanel"
    DB_USER: "root"
    DB_PASSWORD: "testpw"
    SP_INSTALLED: "true"
  tty: true
  stdin_open: true
